from datetime import timedelta
from urllib.parse import urlencode
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import RedirectResponse
from sqlalchemy.orm import Session
from pydantic import BaseModel, EmailStr
from config import settings
from database import get_db
from models.user import User
from models.business import Business
from auth.security import get_password_hash, verify_password, create_access_token
from auth.google_oauth import GoogleOAuthService

router = APIRouter(prefix="/auth", tags=["Authentication"])

# Inbound Request Schemas
class SignupRequest(BaseModel):
    name: str                       # Owner name
    business_name: str              # Company name
    email: EmailStr                 # Workspace Admin unique email
    phone: str                      # Contact line
    password: str                   # Account password

class LoginRequest(BaseModel):
    email: EmailStr
    password: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    user_id: str
    business_id: str
    role: str

@router.post("/signup", response_model=TokenResponse, status_code=status.HTTP_201_CREATED)
def signup(payload: SignupRequest, db: Session = Depends(get_db)):
    """
    Unified Account Setup: Registers a brand-new Company Business profile,
    and binds the initial corporate workspace Owner User account parameters.
    """
    # 1. Block existing email registrations
    existing_user = db.query(User).filter(User.email == payload.email).first()
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An account is already registered with this email address."
        )

    # 2. Persist Business properties in a clean transactional unit
    new_business = Business(
        name=payload.business_name,
        email=payload.email,
        phone=payload.phone
    )
    db.add(new_business)
    db.flush()  # Extract the autogenerated business.id

    # 3. Create, salt/hash password, and save Owner User
    hashed_pwd = get_password_hash(payload.password)
    new_owner = User(
        business_id=new_business.id,
        name=payload.name,
        email=payload.email,
        password_hash=hashed_pwd,
        role="Owner",
        status="Active"
    )
    db.add(new_owner)
    db.commit()
    db.refresh(new_owner)

    # 4. Generate signed authentication claims token
    access_token = create_access_token(
        subject=new_owner.id,
        additional_claims={
            "business_id": new_business.id,
            "role": "Owner"
        }
    )

    return TokenResponse(
        access_token=access_token,
        user_id=new_owner.id,
        business_id=new_business.id,
        role="Owner"
    )

@router.post("/login", response_model=TokenResponse)
def login(payload: LoginRequest, db: Session = Depends(get_db)):
    """
    Core sign-in gateway verifying salted credentials and returning valid signed JWTs.
    """
    user = db.query(User).filter(User.email == payload.email).first()
    if not user or not verify_password(payload.password, user.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password credential details."
        )

    if user.status != "Active":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Your corporate workspace account is currently deactivated."
        )

    access_token = create_access_token(
        subject=user.id,
        additional_claims={
            "business_id": user.business_id,
            "role": user.role
        }
    )

    return TokenResponse(
        access_token=access_token,
        user_id=user.id,
        business_id=user.business_id,
        role=user.role
    )

@router.get("/google/authorize")
def google_authorize():
    """
    Exposes the Google OAuth2 OpenID Connect permission redirect URI.
    """
    redirect_url = GoogleOAuthService.get_authorization_url()
    return {"authorization_url": redirect_url}

def _frontend_redirect(path: str, params: dict) -> RedirectResponse:
    """
    Builds a browser redirect back into the SPA. Auth params ride in the URL
    fragment (#...) so the token never reaches server access logs / referrers.
    """
    fragment = urlencode(params)
    return RedirectResponse(url=f"{settings.FRONTEND_URL}{path}#{fragment}")


@router.get("/google/callback")
async def google_callback(code: str, db: Session = Depends(get_db)):
    """
    Receives Google's code exchange parameter, verifies sub-id credentials,
    re-fetches active User account profiles, or registers brand new tenants,
    then redirects the browser back to the SPA with a signed session token.
    """
    try:
        google_profile = await GoogleOAuthService.exchange_code_for_user_info(code)
    except HTTPException as exc:
        # Surface the failure to the SPA login page instead of a raw JSON error.
        return _frontend_redirect("/login", {"auth_error": str(exc.detail)})

    # Check if this third-party user already possesses an active Autofy profile
    user = db.query(User).filter(User.email == google_profile.email).first()

    if not user:
        # Create a new Business workspace and Active User dynamically if not found (Auto-onboarding)
        new_business = Business(
            name=f"{google_profile.name}'s Studio Suite",
            email=google_profile.email
        )
        db.add(new_business)
        db.flush()
        
        # Salt-hash dummy codes for federated SSO users
        dummy_pwd = get_password_hash(f"sso_google_{google_profile.sub}_auth_safe_2026")
        user = User(
            business_id=new_business.id,
            name=google_profile.name,
            email=google_profile.email,
            password_hash=dummy_pwd,
            role="Owner",
            status="Active"
        )
        db.add(user)
        db.commit()
        db.refresh(user)
    else:
        if user.status != "Active":
            return _frontend_redirect(
                "/login",
                {"auth_error": "Your third-party federated account is currently deactivated."}
            )

    token = create_access_token(
        subject=user.id,
        additional_claims={
            "business_id": user.business_id,
            "role": user.role
        }
    )

    # Hand the browser back to the SPA with the session token + profile.
    return _frontend_redirect(
        "/auth/callback",
        {
            "access_token": token,
            "user_id": user.id,
            "business_id": user.business_id,
            "role": user.role,
            "email": user.email,
            "name": user.name or "",
        }
    )
